figure('OuterPosition',[350,450, 450,450])
plot(1:length(x),x,'o')
ylabel('time (s)')
%         ylabel('MSD ($\AA$)','interpreter','latex')
xlabel('kMC steps')
title(['Fe_{',num2str(100-(i-1)*10),'}Ni_{',num2str((i-1)*10),'}-T=',num2str(T),'K'])
set(gca,'FontSize',12,'Fontname', 'Arial','FontWeight','bold',"LineWidth",2)

figure('OuterPosition',[350,450, 450,450])
plot(1:length(x),MSD_set,'o')
ylabel('MSD ')
%         ylabel('MSD ($\AA$)','interpreter','latex')
xlabel('kMC steps')
title(['Fe_{',num2str(100-(i-1)*10),'}Ni_{',num2str((i-1)*10),'}-T=',num2str(T),'K'])
set(gca,'FontSize',12,'Fontname', 'Arial','FontWeight','bold',"LineWidth",2)